#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
waybar &

# wallpaper

# other
/usr/lib/polkit-gnome/polkit-kde-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
sleep 1
$scripts/wall $config/wallpapers/catalina-night.jpg &
